// <auto-generated />
using System;
using GymResult.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymResult.Migrations
{
    [DbContext(typeof(TrainingInfoContext))]
    [Migration("20230209091958_GymResulInitiaMigtion")]
    partial class GymResulInitiaMigtion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("GymResult.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Klatka",
                            Series = 1,
                            TrainingId = 1,
                            Weight = 95.5
                        },
                        new
                        {
                            Id = 2,
                            Category = "Klatka",
                            Series = 2,
                            TrainingId = 1,
                            Weight = 95.5
                        },
                        new
                        {
                            Id = 3,
                            Category = "Klatka",
                            Series = 3,
                            TrainingId = 1,
                            Weight = 95.5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Klatka",
                            Series = 1,
                            TrainingId = 2,
                            Weight = 95.5
                        },
                        new
                        {
                            Id = 5,
                            Category = "Klatka",
                            Series = 2,
                            TrainingId = 2,
                            Weight = 95.5
                        },
                        new
                        {
                            Id = 6,
                            Category = "Klatka",
                            Series = 1,
                            TrainingId = 3,
                            Weight = 95.5
                        });
                });

            modelBuilder.Entity("GymResult.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 2, 9, 10, 19, 58, 325, DateTimeKind.Local).AddTicks(2915),
                            Description = "Pozytywny",
                            Location = "Kraków"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 2, 9, 10, 19, 58, 325, DateTimeKind.Local).AddTicks(2918),
                            Description = "Pozytywny",
                            Location = "Kraków"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 2, 9, 10, 19, 58, 325, DateTimeKind.Local).AddTicks(2921),
                            Description = "Lekki ból",
                            Location = "Sandomierz"
                        });
                });

            modelBuilder.Entity("GymResult.Models.ExercicesDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("ExercicesDto");
                });

            modelBuilder.Entity("GymResult.Entities.Exercise", b =>
                {
                    b.HasOne("GymResult.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("GymResult.Models.ExercicesDto", b =>
                {
                    b.HasOne("GymResult.Entities.Training", null)
                        .WithMany("Exercies")
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("GymResult.Entities.Training", b =>
                {
                    b.Navigation("Exercies");
                });
#pragma warning restore 612, 618
        }
    }
}
